spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 2MB

minio:
  endpoint: http://localhost:9000/
  user: admin
  password: adminpass
  bucketName: equipments
  maxFileSize: 2097152
