spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 2MB
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: file-service-group

minio:
  endpoint: http://localhost:9000/
  user: admin
  password: adminpass
  bucketName: equipments
  maxFileSize: 2097152

